development:
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
  solr:
    url: http://localhost:8983/solr/development
hypatia-dev:
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@hypatia-dev.stanford.edu:8983/fedora
  solr:
    url: http://hypatia-dev.stanford.edu:8983/solr/development
test: &TEST  
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
  solr:
    url: http://localhost:8983/solr/test
production:
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@your.production.server:8080/fedora
#    url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
  solr:
    url: http://your.production.server:8080/solr 
#    url: http://localhost:8983/solr/development 
cucumber:
  <<: *TEST
