development:
  url: https://sayers.cul.columbia.edu:8443/fedora
  user: fedoraAdmin
  password: f+BULUS*^
#  url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
test: &TEST  
  url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
production:
  url: http://fedoraAdmin:fedoraAdmin@your.production.server:8080/fedora
  #    url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
cucumber:
  <<: *TEST
